# Generated by Django 3.1 on 2021-11-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicledetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicle',
            name='Regid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addvehicle',
            name='photo',
            field=models.ImageField(default=' ', upload_to='addvehicle/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addvehicle',
            name='staticmap',
            field=models.ImageField(upload_to='staticmap/'),
        ),
    ]
