# Generated by Django 3.1 on 2021-11-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicledetail', '0002_auto_20211123_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvehicle',
            name='slug',
            field=models.CharField(default='', max_length=300),
        ),
    ]
